### PR TITLE
complete translate to korean version in 3.21

### PR DESCRIPTION
**Pull request by hwanghakbeom**
xitrum guide 3.21

### CODE REVIEW

**Comment by ngocdaothanh** [comment]
:+1: 
Thanks a lot!
I'll try to build the PDF.

**Comment by ngocdaothanh** [comment]
I've changed directory name from "kr" to "ko", and added you to the list of main authors of Xitrum Guide:
https://github.com/xitrum-framework/xitrum-doc/commits/master

Currently, PDF of Japanese version can be built:
https://github.com/xitrum-framework/xitrum-doc/blob/master/guide/make_latexpdf.sh#L16
https://github.com/xitrum-framework/xitrum-doc/blob/master/guide/Makefile#L113

Although Korean language (and also Chinese language) is in the same group with Japanese language ([CKJ](http://en.wikipedia.org/wiki/CJK_characters)), it seems that building PDF of Korean is not straight forward. I guess it will take some time to solve this problem.

**Comment by ngocdaothanh** [comment]
1.

Because we haven't be able to create the PDF version, for now I think single-page-HTML is a good alternative:
https://github.com/xitrum-framework/xitrum-doc/commit/1c42f5d97aad581d72ed88de461af55a392f043c

I'll publish your Korean translation (multiple-page HTML and single-page-HTML) to the homepage of Xitrum:
http://xitrum-framework.github.io/

2.

Could you please also translate the homepage of Xitrum to Korean?
https://github.com/xitrum-framework/xitrum-framework.github.io

I've added you to the translation team, so that you can edit and publish the Guide Book and home page of Xitrum directly:
https://github.com/orgs/xitrum-framework/teams/xitrum-guide-book-team

You can clone the repos and push to the repos directly:
https://github.com/xitrum-framework/xitrum-doc
https://github.com/xitrum-framework/xitrum-framework.github.io

Every time you push to https://github.com/xitrum-framework/xitrum-framework.github.io, the home page will be updated automatically.

**Comment by ngocdaothanh** [comment]
I've published:
http://xitrum-framework.github.io/guide.html
http://xitrum-framework.github.io/index.html (scroll down to the Xitrum Guide section)

Andy Hwang, thanks again for your contribution! :+1:

**Comment by georgeOsdDev** [comment]
:clap:

**Comment by ngocdaothanh** [comment]
@hwanghakbeom 
Hi Andy,

Son Hoang (@wingadium1), the author of the Vietnamese version, has just found a way to create the PDF:
https://drive.google.com/file/d/0B4nP_B5KDxyPSVlNNnMtNVBpNGc/view?usp=sharing

I'm asking him how he did it.
I'll update info to the [README](https://github.com/xitrum-framework/xitrum-doc/blob/master/guide/README.rst) and publish the Korean PDF file soon.

Happy Lunar New Year!

**Comment by hwanghakbeom** [comment]
thanks.

Happy new year !!

나의 iPhone에서 보냄

2015. 2. 25. 오전 7:35 Ngoc Dao <notifications@github.com> 작성:

**Comment by wingadium1** [comment]
@hwanghakbeom 

I has just build a PDF export of Xitrum guild in Korean and I found that that there was some mistake in that PDF. I think it may be from *.rst source, can you check that?

You can build a PDF version yourself too. you may try : use ``make_latexpdf.sh`` script to generate, after that in ``xitrum.tex`` file (``_build/latex`` dir),  remove line ``\usepackage{babel}`` and add ``\usepackage{kotex}``, It works well for me.

Happy new year !!

**Comment by ngocdaothanh** [comment]
@hwanghakbeom 
By "mistake", I think @wingadium1 wants to say that some links are not displayed correctly, like this:

link

I think you need to add one space between Korean character and the link delimiter.

For example, try to change:

```
... Xitrum 정적 파일 전송 속도는`Nginx와 동등 <https://gist.github.com/3293596>`_ 합니다 ...
```

to:

```
... Xitrum 정적 파일 전송 속도는 `Nginx와 동등 <https://gist.github.com/3293596>`_ 합니다 ...
```

And:

```
:doc:`Akka 클러스터링 </cluster>`을 참고하세요.
```

to:

```
:doc:`Akka 클러스터링 </cluster>` 을 참고하세요.
```

**Comment by hwanghakbeom** [comment]
thanks for let me know it

I will check the 'space' on the korean docs 

나의 iPhone에서 보냄

2015. 2. 26. 오전 8:24 Ngoc Dao <notifications@github.com> 작성:

**Comment by ngocdaothanh** [comment]
@hwanghakbeom

I'm very happy to let you know that Korean PDF can be generated normally, by adding kotex package to the .tex file generated by Sphinx.

I've added a script to add the package automatically when running `make_latexpdf.sh`:
https://github.com/xitrum-framework/xitrum-doc/commit/2bec0e7d9eaa018a53aeb4096a3842b7022e865c

**Pull request merged**
